info:
  name: docker-id-open-webui
  group: STAR
repository:
  format: none
  usage: none
jobs:
  jenkinsfile:
    - name: build-and-register
      file: jenkins/buildAndRegister
      upstream:
        scmBranch: dev
        scm: true