info:
  name: docker-id-open-webui
  group: STAR
repository:
  format: none
  usage: none
jobs:
  jenkinsfile:
    - name: build-and-register-dev
      file: jenkins/buildAndRegisterDev
      upstream:
        scmBranch: dev
        scm: true
    - name: build-and-register-prod
      file: jenkins/buildAndRegister
      upstream:
        scmBranch: master
        scm: true
