info:
  name: docker-id-open-webui
  group: STAR
repository:
  format: none
  usage: none
jobs:
  jenkinsfile:
    - name: build-and-register-dev
      file: jenkins/buildAndRegisterDevelop
      upstream:
        scmBranch: develop
        scm: true
    - name: build-and-register-prod  
      file: jenkins/buildAndRegister
      upstream:
        scmBranch: master
        scm: true





        